---
- name: This playbook creates user
  hosts: all
  become: yes

  vars_files:
  - user.yml        

  tasks:
  - name: creating a user "{{user}}"
    user: 
     name="{{user}}"
     state=present
...      
