---
- name: installing httpd
  hosts: all
  become: true

  tasks:
  - name: installing httpd
    yum: 
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: installing apache2 package
    apt:
      name: apache2
      state: present
    notify: starting apache2 service
    when: ansible_os_family == "Debian"

  - name: coying index.html file
    copy:
      src: /home/ansible/index.html
      dest: /var/www/html/
      mode: 0666
      
  - name: starting httpd service
    service:
      name: htt
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes  

  - name: starting apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
