---
- name: uninstalling httpd
  hosts: all
  become: true

  tasks:
  - name: stoppind httpd
    service:
      name: httpd
      state: stopped
  - name: uninstalling httpd
    yum:
      name: httpd
      state: removed
