---
# tasks file for setup-apache-role

  - name: installing httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: starting httpd service

  - name: installing apache2 package
    apt:
      name: apache2
      state: present
    notify: starting apache2 service
    when: ansible_os_family == "Debian"

